# Site settings
title: minsik's blog
header-img: img/home-bg.jpg
email: yms9654@gmail.com
description: "about software development"
url: "https://yms9654.github.io"
twitter_username: yms9654
github_username:  yms9654

# Build settings
markdown: redcarpet
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","README.md", "vendor/bundle", "_posts/template.md"]
